name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Lint and test
        run: |
          npm run lint  # ถ้ามี ESLint
          npm run test  # ถ้ามี Unit test ด้วย Vitest หรือ Jest

      - name: Build
        run: npm run build